# Generated by Django 2.1.1 on 2020-03-24 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=240)),
                ('product', models.CharField(max_length=240)),
                ('year', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ImageField(upload_to='image_pics')),
            ],
        ),
    ]
