# Generated by Django 2.1.1 on 2020-03-24 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashion',
            name='year',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
