# Generated by Django 2.1.1 on 2020-03-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anoapp', '0002_auto_20200324_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashion',
            name='image',
            field=models.ImageField(default='image_pics/default.jpg', upload_to='image_pics/'),
        ),
    ]
