# Generated by Django 2.1.1 on 2020-04-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anoapp', '0007_remove_fashion_image1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image_pics/default.jpg', upload_to='image_pics/')),
            ],
        ),
    ]
