# Generated by Django 2.1.1 on 2020-04-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anoapp', '0008_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashion',
            name='image',
        ),
    ]
