# Generated by Django 2.1.1 on 2020-04-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anoapp', '0009_remove_fashion_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='fashion',
            name='image',
            field=models.ImageField(default='image_pics/default.jpg', upload_to='image_pics/'),
        ),
    ]
