# Generated by Django 2.1.1 on 2020-04-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anoapp', '0011_auto_20200406_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
    ]
