# Generated by Django 2.1.1 on 2020-04-06 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anoapp', '0012_remove_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='anoapp.Fashion'),
            preserve_default=False,
        ),
    ]
